name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '23.2'
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build -- --base-href=/wsd_netflix_clone/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist/your-project-name
    - name: Create GitHub Deployment
      uses: chrnorm/deployment-action@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        environment: production
        initial-status: success
        target-url: ${{ steps.deployment.outputs.url }}